apiVersion: batch/v1
kind: Job
metadata:
  name: waymo-miner
spec:
  # Each completion gets a unique index; your code reads JOB_COMPLETION_INDEX
  completionMode: Indexed
  completions: 100            # == SHARD_COUNT (adjust)
  parallelism: 20             # how many shards run concurrently
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      # If your image is private, uncomment:
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: miner
        image: yourname/waymo-miner:py38
        imagePullPolicy: IfNotPresent
        env:
          # S3 config your script expects
          - name: BUCKET
            value: "waymo"
          - name: INPUT_PREFIX
            value: "tfrecords/"   # or an exact key to test one file
          - name: RESULT_PREFIX
            value: "results/k8s-run-001/"
          - name: SHARD_COUNT
            value: "100"          # must match spec.completions
          - name: MAX_UPLOAD_THREADS
            value: "8"
          # Trust the corporate CA inside the pod
          - name: AWS_CA_BUNDLE
            value: <>
        envFrom:
          - secretRef:
              name: aws-creds
        volumeMounts:
          - name: <>
            mountPath: <>
            readOnly: true
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
            ephemeral-storage: "10Gi"  # temp download space for TFRecords
          limits:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "30Gi"
      volumes:
        - name: iav-ca
          secret:
            secretName: iav-ca